import test from 'node:test';
import assert from 'node:assert/strict';
import * as M from '../inventory.mjs';
const day = '2026-09-09';
const fixture = (changes = {}) => ({id:'sample-1',name:'Example A',strength:'',quantity:30,dailyUse:1,mode:'daily',countedOn:day,leadDays:7,lowCount:5,packSize:30,ordered:false,...changes});

test('inventory module exposes the stock projection', () => assert.equal(typeof M.project, 'function'));
test('count date does not deduct a second daily amount', () => assert.equal(M.project(fixture(),day).remaining,30));
test('daily stock catches up after five unopened days', () => assert.equal(M.project(fixture(),'2026-09-14').remaining,25));
test('stock never becomes negative after a long absence', () => assert.equal(M.project(fixture(),'2027-09-09').remaining,0));
test('half-pill use stays exact', () => assert.equal(M.project(fixture({quantity:10.5,dailyUse:0.5}),'2026-09-12').remaining,9));
test('quarter-pill quantities stay exact', () => assert.equal(M.project(fixture({quantity:1,dailyUse:0.25}),'2026-09-12').remaining,0.25));
test('only complete days count towards cover', () => assert.equal(M.project(fixture({quantity:3,dailyUse:2}),day).daysLeft,1));
test('refill threshold includes the exact boundary', () => assert.equal(M.project(fixture({quantity:7}),day).needsRefill,true));
test('stock above the threshold is not low', () => assert.equal(M.project(fixture({quantity:8}),day).needsRefill,false));
test('first short day and refill-by day are distinct', () => {const p=M.project(fixture(),day);assert.equal(p.firstShortDay,'2026-10-10');assert.equal(p.refillOn,'2026-10-02');});
test('manual tracking does not assume daily consumption', () => {const p=M.project(fixture({mode:'manual',dailyUse:0}),'2026-10-09');assert.equal(p.remaining,30);assert.equal(p.daysLeft,null);});
test('manual stock uses its count threshold', () => assert.equal(M.project(fixture({mode:'manual',dailyUse:0,quantity:5}),day).needsRefill,true));
test('future count dates produce an explicit clock warning', () => {const p=M.project(fixture({countedOn:'2026-09-10'}),day);assert.equal(p.clockWarning,true);assert.equal(p.remaining,30);});
test('calendar days do not vary over Melbourne daylight saving', () => assert.equal(M.daysBetween('2026-10-03','2026-10-05'),2));
test('leap days are valid', () => assert.equal(M.daysBetween('2028-02-28','2028-03-01'),2));
test('impossible dates are rejected', () => assert.throws(()=>M.daysBetween('2026-02-30',day),/calendar date/));
test('Melbourne day is independent of host timezone', () => assert.equal(M.todayInMelbourne(new Date('2026-09-08T15:30:00Z')),day));
test('refill adds to the current estimate, not the original count', () => {const m=M.updateStock(fixture({ordered:true}),'refill',30,'2026-09-14');assert.equal(m.quantity,55);assert.equal(m.countedOn,'2026-09-14');assert.equal(m.ordered,false);});
test('recount corrects the balance rather than adding', () => assert.equal(M.updateStock(fixture(),'count',9,day).quantity,9));
test('manual use subtracts only the entered amount', () => assert.equal(M.updateStock(fixture({mode:'manual',dailyUse:0}),'use',0.5,day).quantity,29.5));
test('manual use cannot exceed stock', () => assert.throws(()=>M.updateStock(fixture({mode:'manual',dailyUse:0}),'use',31,day),/exceed/));
test('manual use cannot double-deduct a daily estimate', () => assert.throws(()=>M.updateStock(fixture(),'use',1,day),/already account/));
test('negative, nonfinite and non-quarter quantities are rejected', () => {for (const quantity of [-1,NaN,Infinity,0.1,'30']) assert.throws(()=>M.validateMedicine(fixture({quantity})),/steps of/);});
test('a daily forecast requires nonzero daily use', () => assert.throws(()=>M.validateMedicine(fixture({dailyUse:0})),/Daily use/));
test('very large stock is rejected', () => assert.throws(()=>M.validateMedicine(fixture({quantity:100001})),/Quantity/));
test('missing or whitespace-only names are rejected', () => assert.throws(()=>M.validateMedicine(fixture({name:'   '})),/name/));
test('Unicode and quoted names survive validation unchanged', () => assert.equal(M.validateMedicine(fixture({name:'Test "A" - தமிழ்'})).name,'Test "A" - தமிழ்'));
test('backup validation rejects duplicate IDs', () => assert.throws(()=>M.validateState({...M.emptyState(),medicines:[fixture(),fixture()]}),/duplicate/));
test('backup validation rejects future schema versions', () => assert.throws(()=>M.validateState({...M.emptyState(),version:2}),/supported/));
test('backup validation drops unknown properties', () => assert.equal(M.validateState({...M.emptyState(),extra:'x'}).extra,undefined));
test('restocks respect the maximum stock bound', () => assert.throws(()=>M.updateStock(fixture({quantity:100000}),'refill',1,day),/Quantity/));
test('zero refill quantities are rejected', () => assert.throws(()=>M.updateStock(fixture(),'refill',0,day),/Amount/));
test('first short day remains anchored after stock reaches zero', () => assert.equal(M.project(fixture({quantity:3,dailyUse:2}),'2026-09-14').firstShortDay,'2026-09-11'));
test('refill date does not drift forwards after running out', () => assert.equal(M.project(fixture(),'2026-11-01').refillOn,'2026-10-02'));
